fastlane_version "2.37.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  lane :changeLog do
	v2_changelog = changelog_from_git_commits(
	pretty: '%ai %h -%d %s <%an>',
	date_format: "short",
	between: [“v0”, “HEAD”])
	
	File.open('ReleaseNotes.txt', 'w') { |file| 		
	file.write(v2_changelog) }
  end

  lane :beta do
    #cert()
    sigh(
	app_identifier:’com.brainbeanapps.HelloWorld’)
    clear_derived_data(
	derived_data_path: './DerivedData')
    gym(
        scheme: ‘IDMaps’,
	clean: true,
	derived_data_path: './DerivedData’)
    clear_derived_data(
	derived_data_path: './DerivedData')
    end


  after_all do |lane|
	changeLog()
  end

  error do |lane, exception|
  end
end
