fastlane_version "2.39.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  lane :changeLog do
v2_changelog = generate_release_changelog(
  github_project: 'igoronix/IDMaps',
  github_api_token: '4756c6b6ecb19942a4c42d05c31ecb9ce223b879',
  base_branch: 'master',
  template_path: 'fastlane/changelog_template.erb',
  tag_a: 'v3’,
  tag_b: 'v0', # Optional, will be prompted if not provided
  #skip_tag_b: true, # Optional, defaults to false
  output_path: 'RELEASE_1.md' # Optional
)
end

  lane :changeLog2 do
	v2_changelog = changelog_from_git_commits(
	pretty: '%ai %h -%d %s <%an>',
	date_format: "short",
	between: [“v0”, “v3”])
	
	File.open('ReleaseNotes.txt', 'w') { |file| 		
	file.write(v2_changelog) }
  end

  lane :beta do
    cert()
    sigh(
	app_identifier:’com.id.idmaps’)
    clear_derived_data(
	derived_data_path: './DerivedData')
    gym(
        scheme: ‘IDMaps’,
	clean: true,
	derived_data_path: './DerivedData’)
    end


  after_all do |lane|
	changeLog()
  end

  error do |lane, exception|
  end
end
